"""users table

Revision ID: 115f3e1fe0f4
Revises: 539b17efe8aa
Create Date: 2021-04-17 15:49:13.409225

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '115f3e1fe0f4'
down_revision = '539b17efe8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('description', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('user', sa.Column('tenancy', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tenancy')
    op.drop_column('user', 'location')
    op.drop_column('user', 'description')
    # ### end Alembic commands ###
