"""empty message

Revision ID: 539b17efe8aa
Revises: 
Create Date: 2021-04-17 13:11:00.241977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '539b17efe8aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('institution', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_institution'), 'user', ['institution'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_institution'), table_name='user')
    op.drop_column('user', 'institution')
    # ### end Alembic commands ###
